name: OneClickDocs-Install

run-name: Install Docs on pure environment

on:
  workflow_dispatch:
    
jobs:
  get-version:
    name: "Get ds version for test"
    runs-on: ubuntu-latest
    outputs:
      ds-ver: ${{ steps.get-version.outputs.ds-ver }}
    steps:
    - name: get-version
      id: get-version
      shell: bash
      run: |
          if curl -s -L -H "Accept: application/vnd.github+json" https://api.github.com/repos/ONLYOFFICE/document-server-package/branches | jq -r '.[].name' | grep -qE '^release/'; then
            VERSION=$(curl -s -L -H "Accept: application/vnd.github+json" https://api.github.com/repos/ONLYOFFICE/document-server-package/branches | jq -r '.[] | select(.name|test("^release/")) | .name' | awk -F '/v' '{print $2}')  
          else
            VERSION=$(curl -s -L -H "Accept: application/vnd.github+json" https://api.github.com/repos/ONLYOFFICE/document-server-package/branches | jq -r '.[] | select(.name|test("^hotfix/")) | .name' | awk -F '/v' '{print $2}')
          fi
          echo "ds-ver=${VERSION:-99.99.99}" >> "$GITHUB_OUTPUT"

  vagrant-up:
    name: "Test Docs with ${{matrix.name}}"
    needs: [get-version]
    runs-on: ubuntu-latest
    env:
      VER: ${{ needs.get-version.outputs.ds-ver }}
    strategy:
      fail-fast: false
      matrix:
        include:          
          - distr: unclebob
            os: centos9s
            name: "centos9s"

          - distr: unclebob
            os: debian12
            name: "debian12"         

          - distr: unclebob
            os: fedora40
            name: "fedora40"               

          - distr: unclebob
            os: fedora41
            name: "fedora41"

          - distr: unclebob
            os: ubuntu2204
            name: "ubuntu2204"

          - distr: unclebob
            os: ubuntu2404
            name: "ubuntu2404"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Test production scripts
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 40
        retry_on: error
        command: |
                set -eux
                
                cd tests/vagrant
                   TEST_CASE='--production-install' \
                   DISTR='${{ matrix.distr }}' \
                   OS='${{ matrix.os }}' \
                   DOWNLOAD_SCRIPT='-ds true' \
                   RAM='6000' \
                   CPU='3' \
                   ARGUMENTS="-arg '--skiphardwarecheck true --makeswap false'" \
                   vagrant up
        on_retry_command: |
              echo "RUN CLEAN UP: Destroy vagrant and one more try"
              cd tests/vagrant
              sleep 10
              vagrant destroy --force
