name: Rebuild vagrant Docs

run-name: "Rebuild boxes ${{ github.event.inputs.box-version }}"

on:
  workflow_dispatch:
    inputs:
      box-version:
         type: string
         description: 'Docs version that will be installed inside box'
         required: true
      centos7:
         type: boolean
         description: 'CentOS 7'
         default: true
      centos8s:
         type: boolean
         description: 'CentOS 8 Stream'
         default: true 
      centos9s:
         type: boolean
         description: 'CentOS 9 Stream'
         default: true
      debian10:
         type: boolean
         description: 'Debian 10'
         default: true
      debian11:
         type: boolean
         description: 'Debian 11'
         default: true
      debian12:
         type: boolean
         description: 'Debian 12'
         default: true
      ubuntu1804:
         type: boolean
         description: 'Ubuntu18.04'
         default: true
      ubuntu2004:
         type: boolean
         description: 'Ubuntu 20.04'
         default: true
      ubuntu2204:
         type: boolean
         description: 'Ubuntu 22.04'
         default: true
      ubuntu2404:
         type: boolean
         description: 'Ubuntu 24.04'
         default: true
         
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix names
        id: set-matrix
        run: |
          # NOTE: name should be the same as os, but without base-
          # For example os: base-centos7 >> name: centos7
          matrix=$(echo '{
            "include": [
              {"execute": '${{ github.event.inputs.centos7 || true }}', "name": "centos7", "os": "base-centos7", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.centos8s || true }}', "name": "centos8s", "os": "base-centos8s", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.centos9s || true }}', "name": "centos9s", "os": "base-centos9s", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian10 || true }}', "name": "debian10", "os": "base-debian10", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian11 || true }}', "name": "debian11", "os": "base-debian11", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian12 || true }}', "name": "debian12", "os": "base-debian12", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu1804 || true }}', "name": "ubuntu1804", "os": "base-ubuntu1804", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu2004 || true }}', "name": "ubuntu2004", "os": "base-ubuntu2004", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu2204 || true }}', "name": "ubuntu2204", "os": "base-ubuntu2204", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu2404 || true }}', "name": "ubuntu2404", "os": "base-ubuntu2404", "distr": "onlyoffice"}
            ]
          }' | jq -c '{include: [.include[] | select(.execute == true)]}')
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          
  vagrant-up:
    name: "Rebbuild Docs ${{matrix.name}}"
    needs: ['prepare']
    runs-on: ubuntu-latest
    env:
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      BOX_VERSION: ${{ github.event.inputs.box-version }}
      VAGRANT_ORG: unclebob
      PRODUCT: docs
      OS_NAME: ${{ matrix.name }}
      OS: ${{ matrix.os }}
      DISTR: ${{ matrix.distr }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare.outputs.matrix)}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 'Download hcp CLI'
      uses: 'hashicorp/hcp-setup-action@v0'
      with:
        version: 'latest'

    - name: Set up vagrant and virtualbox
      run: |
           curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
           echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
           sudo apt update -y 
           sudo apt install vagrant virtualbox -y

    - name: Test production scripts
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 40
        retry_on: error
        command: |
                set -eux
                
                cd tests/vagrant
                   TEST_CASE='--production-install' \
                   DISTR='${{ matrix.distr }}' \
                   OS='${{ matrix.os }}' \
                   DOWNLOAD_SCRIPT='-ds true' \
                   RAM='6000' \
                   CPU='3' \
                   ARGUMENTS="-arg '--skiphardwarecheck true --makeswap false'" \
                   vagrant up
                   sleep 100
                   vagrant package --output ${PRODUCT}-${OS_NAME}.box
                   bash ./publish.sh
        on_retry_command: |
              echo "RUN CLEAN UP: Destroy vagrant and one more try"
              cd tests/vagrant
              sleep 10
              vagrant destroy --force
